spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: file:///home/xanax/Desktop/projects/stromae-config-repo
          default-label: main
          search-paths: configs

server:
  port: 8888

management:
  endpoints:
    web:
      exposure:
        include: health, info, refresh
  endpoint:
    health:
      show-details: always
