spring:
  cloud:
    config:
      server:
        git:
          cloneOnStart: true

---
spring:
  config:
    activate:
      on-profile: docker
  cloud:
    config:
      server:
        git:
          cloneOnStart: true
